### ISSUE TITLE
Message Age Issue

### ISSUE THREAD

**Issue by OlivierJ73** [shemminger/RSTP#4]
Hi Stephen

I have one issue with the Message age calculation:
in rolesel.c
 l 158 we have
       dm = (8 +  stpm->rootTimes.MaxAge) / 16;
      if (!dm)
        dm = 1;

I think we should have only dm = 1;
It look like message age depend on the MaxAge defined by the root bridge. So if you increase the MaxAge to 24, the message age will increase each time with 2s ... So the MaxAge will be reached too quickly

Thank you

Olivier

**Comment by shemminger** [comment]
This package is end of life and no longer supported.
I recommend investigating MSTP insteadl
